# Malnati/ops-sonarq@v1.0.0
name: "Ops SonarQ"
description: "Scan with idempotence."
author: "Ricardo Malnati"

branding:
  icon: "eye"
  color: "orange"

inputs:
  path:
    description: Path to scan
    required: true
    default: "api"
  project_key:
    description: Project key
    required: false
    default: "nome-do-projeto"
  project_name:
    description: Project name
    required: false
    default: "Nome do Projeto"

outputs:
  report_path:
    description: "Path to the generated report directory."
    value: ${{ steps.generate_output.outputs.report_path }}
  status:
    description: "Quality Gate status."
    value: ${{ steps.generate_output.outputs.status }}

runs:
  using: "composite"
  steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set scan path
        id: config
        shell: bash
        env:
          INPUT_PATH: ${{ inputs.path }}
        run: bash assets/sonarq-set-scan-path.sh

      - name: Detect SonarQube Host
        id: sonar-host
        shell: bash
        run: bash assets/sonarq-detect-host.sh

      - name: Wait for SonarQube to be ready
        shell: bash
        run: bash assets/sonarq-wait-ready.sh

      - name: Configure SonarQube Project
        shell: bash
        env:
          INPUT_PROJECT_KEY: ${{ inputs.project_key }}
          INPUT_PROJECT_NAME: ${{ inputs.project_name }}
        run: bash assets/sonarq-configure-project.sh

      - name: Download and Setup Sonar Scanner
        shell: bash
        run: bash assets/sonarq-setup-scanner.sh

      - name: Verify Source Directory
        shell: bash
        run: bash assets/sonarq-verify-source.sh

      - name: Run SonarQube Scan
        shell: bash
        run: bash assets/sonarq-run-scan.sh

      - name: Wait for Analysis Processing
        shell: bash
        run: bash assets/sonarq-wait-analysis.sh

      - name: Create Report Directory
        shell: bash
        run: bash assets/sonarq-create-report-dir.sh

      - name: Extract SonarQube Report
        shell: bash
        run: bash assets/sonarq-extract-report.sh

      - name: Generate Detailed Markdown Report
        id: generate_output
        shell: bash
        run: |
          bash assets/sonarq-generate-report.sh
          scan_path="${SCAN_PATH:-api}"
          report_dir="${scan_path}/.sonarq"
          echo "report_path=$report_dir" >> "$GITHUB_OUTPUT"
          if [ -f "$report_dir/quality-gate.json" ]; then
            qg_status=$(grep -oP '"status"\s*:\s*"\K[^"]+' "$report_dir/quality-gate.json" 2>/dev/null | head -1 || echo "NONE")
          else
            qg_status="NONE"
          fi
          echo "status=$qg_status" >> "$GITHUB_OUTPUT"

      - name: Verify Report Files
        shell: bash
        run: bash assets/sonarq-verify-report.sh

      - name: Commit Report via Pull Request
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: bash assets/sonarq-commit-report.sh

      - name: Upload Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sonarqube-report
          path: |
            ${{ steps.config.outputs.scan_path }}/.sonarq/
          retention-days: 30
