# Malnati/ops-sonarq@v1.0.0
name: "Ops SonarQ"
description: "Scan with idempotence."
author: "Ricardo Malnati"

branding:
  icon: "eye"
  color: "orange"

inputs:
  token:
    description: "GitHub token."
    required: true
  file_extensions:
    description: "Regex of extensions."
    required: false
    default: "ts|js|jsx|tsx|java|py|go|cs|php|sh|json|yaml|yml"
  target_path:
    description: "Directory paths or files to be investigated."
    required: true
    default: "."
  exclude_patterns:
    description: "Regex of ignored."
    required: false
    default: "node_modules|dist|build|.git"

outputs:
  json:
    description: "Generated JSON file path (array)."
    value: ${{ steps.generate_output.outputs.json }}
  report_path:
    description: "Generated JSON file path (array)."
    value: ${{ steps.generate_output.outputs.report_path }}
  status:
    description: "Scan status."
    value: ${{ steps.generate_output.outputs.status }}
  count:
    description: "Number of literals found."
    value: ${{ steps.generate_output.outputs.count }}

runs:
  using: "composite"
  steps:
